import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const monte = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full border-solid overflow-x-hidden">
      <body className={monte.className + " w-full bg-brand-dark"}>
        {children}
      </body>
    </html>
  );
}
